# Generated by Django 4.0.3 on 2022-03-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='decription',
        ),
    ]
