# Generated by Django 4.0.3 on 2022-03-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_remove_nft_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='eth_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
