# Generated by Django 4.0.3 on 2022-03-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_alter_nft_eth_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='eth_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=9, null=True),
        ),
    ]
