# Generated by Django 4.0.3 on 2022-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0004_alter_nft_eth_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='tags',
        ),
        migrations.AddField(
            model_name='nft',
            name='tag1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='tag2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='tag3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='tag4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
