# Generated by Django 4.0.3 on 2022-03-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0005_remove_nft_tags_nft_tag1_nft_tag2_nft_tag3_nft_tag4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
