# Generated by Django 4.0.3 on 2022-03-30 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EthBalance',
            fields=[
                ('eth_balance', models.DecimalField(decimal_places=10, default=0.0, max_digits=13)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
