# Generated by Django 4.0.3 on 2022-03-30 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethbalance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
