# Generated by Django 4.0.3 on 2022-04-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0002_alter_ethbalance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethbalance',
            name='eth_balance',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
        ),
    ]
