# Generated by Django 4.0.3 on 2022-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0003_alter_ethbalance_eth_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethbalance',
            name='eth_balance',
            field=models.DecimalField(blank=True, decimal_places=20, default=1.7e-07, max_digits=30, null=True),
        ),
    ]
