# Generated by Django 4.0.3 on 2022-04-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0007_alter_ethbalance_eth_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethbalance',
            name='eth_balance',
            field=models.DecimalField(decimal_places=5, max_digits=7, null=True),
        ),
    ]
