# Generated by Django 4.0.3 on 2022-04-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0008_alter_ethbalance_eth_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethbalance',
            name='eth_balance',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=7, null=True),
        ),
    ]
